// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
	"time"
)

type Organisation struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	CreatedBy     sql.NullString `json:"created_by"`
	CreatedOnUtc  time.Time      `json:"created_on_utc"`
	ModifiedOnUtc time.Time      `json:"modified_on_utc"`
	ModifiedBy    sql.NullString `json:"modified_by"`
}

type OrganisationToken struct {
	ID             string         `json:"id"`
	OrganisationID string         `json:"organisation_id"`
	Token          string         `json:"token"`
	CreatedBy      string         `json:"created_by"`
	CreatedOnUtc   time.Time      `json:"created_on_utc"`
	ModifiedOnUtc  time.Time      `json:"modified_on_utc"`
	ModifiedBy     sql.NullString `json:"modified_by"`
}

type ScimGroup struct {
	ID               string         `json:"id"`
	ExternalID       sql.NullString `json:"external_id"`
	DisplayName      string         `json:"display_name"`
	MetaResourceType string         `json:"meta_resource_type"`
	MetaCreated      string         `json:"meta_created"`
	MetaLastModified string         `json:"meta_last_modified"`
	MetaVersion      sql.NullString `json:"meta_version"`
	OrganisationID   string         `json:"organisation_id"`
}

type ScimUser struct {
	ID                  string         `json:"id"`
	ExternalID          sql.NullString `json:"external_id"`
	UserName            string         `json:"user_name"`
	DisplayName         sql.NullString `json:"display_name"`
	NickName            sql.NullString `json:"nick_name"`
	ProfileUrl          sql.NullString `json:"profile_url"`
	Title               sql.NullString `json:"title"`
	UserType            sql.NullString `json:"user_type"`
	PreferredLanguage   sql.NullString `json:"preferred_language"`
	Locale              sql.NullString `json:"locale"`
	Timezone            sql.NullString `json:"timezone"`
	Active              bool           `json:"active"`
	Password            sql.NullString `json:"password"`
	MetaResourceType    string         `json:"meta_resource_type"`
	MetaCreated         string         `json:"meta_created"`
	MetaLastModified    string         `json:"meta_last_modified"`
	MetaVersion         sql.NullString `json:"meta_version"`
	NameFormatted       sql.NullString `json:"name_formatted"`
	NameFamilyName      sql.NullString `json:"name_family_name"`
	NameGivenName       sql.NullString `json:"name_given_name"`
	NameMiddleName      sql.NullString `json:"name_middle_name"`
	NameHonorificPrefix sql.NullString `json:"name_honorific_prefix"`
	NameHonorificSuffix sql.NullString `json:"name_honorific_suffix"`
	EmployeeNumber      sql.NullString `json:"employee_number"`
	Organization        sql.NullString `json:"organization"`
	Department          sql.NullString `json:"department"`
	Division            sql.NullString `json:"division"`
	CostCenter          sql.NullString `json:"cost_center"`
	ManagerID           sql.NullString `json:"manager_id"`
	OrganisationID      string         `json:"organisation_id"`
}

type ScimUserEmail struct {
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
	Value        string         `json:"value"`
	Display      sql.NullString `json:"display"`
	Type         sql.NullString `json:"type"`
	PrimaryEmail sql.NullBool   `json:"primary_email"`
}

type ScimUserGroupMembership struct {
	UserID  string `json:"user_id"`
	GroupID string `json:"group_id"`
}

type ScimUserPhoneNumber struct {
	ID                 string         `json:"id"`
	UserID             string         `json:"user_id"`
	Value              string         `json:"value"`
	Display            sql.NullString `json:"display"`
	Type               sql.NullString `json:"type"`
	PrimaryPhoneNumber sql.NullBool   `json:"primary_phone_number"`
}

type User struct {
	ID            string         `json:"id"`
	Username      string         `json:"username"`
	Email         string         `json:"email"`
	Password      string         `json:"password"`
	CreatedBy     sql.NullString `json:"created_by"`
	CreatedOnUtc  time.Time      `json:"created_on_utc"`
	ModifiedOnUtc time.Time      `json:"modified_on_utc"`
	ModifiedBy    sql.NullString `json:"modified_by"`
}

type UserOrganisation struct {
	UserID         string    `json:"user_id"`
	OrganisationID string    `json:"organisation_id"`
	CreatedOnUtc   time.Time `json:"created_on_utc"`
	ModifiedOnUtc  time.Time `json:"modified_on_utc"`
}
