// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
	"time"
)

type Organisation struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	CreatedBy     sql.NullString `json:"created_by"`
	CreatedOnUtc  time.Time      `json:"created_on_utc"`
	ModifiedOnUtc time.Time      `json:"modified_on_utc"`
	ModifiedBy    sql.NullString `json:"modified_by"`
}

type User struct {
	ID            string         `json:"id"`
	Username      string         `json:"username"`
	Email         string         `json:"email"`
	Password      string         `json:"password"`
	CreatedBy     sql.NullString `json:"created_by"`
	CreatedOnUtc  time.Time      `json:"created_on_utc"`
	ModifiedOnUtc time.Time      `json:"modified_on_utc"`
	ModifiedBy    sql.NullString `json:"modified_by"`
}

type UserOrganisation struct {
	UserID         string    `json:"user_id"`
	OrganisationID string    `json:"organisation_id"`
	CreatedOnUtc   time.Time `json:"created_on_utc"`
	ModifiedOnUtc  time.Time `json:"modified_on_utc"`
}
