// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
	"time"
)

type Organisation struct {
	ID            string
	Name          string
	CreatedBy     sql.NullString
	CreatedOnUtc  time.Time
	ModifiedOnUtc time.Time
	ModifiedBy    sql.NullString
}

type OrganisationToken struct {
	ID             string
	OrganisationID string
	Token          string
	CreatedBy      string
	CreatedOnUtc   time.Time
	ModifiedOnUtc  time.Time
	ModifiedBy     sql.NullString
}

type ScimGroup struct {
	ID               string
	ExternalID       sql.NullString
	DisplayName      string
	MetaResourceType string
	MetaCreated      string
	MetaLastModified string
	MetaVersion      sql.NullString
	OrganisationID   string
}

type ScimUser struct {
	ID                  string
	ExternalID          sql.NullString
	UserName            string
	DisplayName         sql.NullString
	NickName            sql.NullString
	ProfileUrl          sql.NullString
	Title               sql.NullString
	UserType            sql.NullString
	PreferredLanguage   sql.NullString
	Locale              sql.NullString
	Timezone            sql.NullString
	Active              bool
	Password            sql.NullString
	MetaResourceType    string
	MetaCreated         string
	MetaLastModified    string
	MetaVersion         sql.NullString
	NameFormatted       sql.NullString
	NameFamilyName      sql.NullString
	NameGivenName       sql.NullString
	NameMiddleName      sql.NullString
	NameHonorificPrefix sql.NullString
	NameHonorificSuffix sql.NullString
	EmployeeNumber      sql.NullString
	Organization        sql.NullString
	Department          sql.NullString
	Division            sql.NullString
	CostCenter          sql.NullString
	ManagerID           sql.NullString
	OrganisationID      string
}

type ScimUserEmail struct {
	ID           string
	UserID       string
	Value        string
	Display      sql.NullString
	Type         sql.NullString
	PrimaryEmail sql.NullBool
}

type ScimUserGroupMembership struct {
	UserID  string
	GroupID string
}

type ScimUserPhoneNumber struct {
	ID                 string
	UserID             string
	Value              string
	Display            sql.NullString
	Type               sql.NullString
	PrimaryPhoneNumber sql.NullBool
}

type User struct {
	ID            string
	Username      string
	Email         string
	Password      string
	CreatedBy     sql.NullString
	CreatedOnUtc  time.Time
	ModifiedOnUtc time.Time
	ModifiedBy    sql.NullString
}

type UserOrganisation struct {
	UserID         string
	OrganisationID string
	CreatedOnUtc   time.Time
	ModifiedOnUtc  time.Time
}
