// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: organisation_user.sql

package repository

import (
	"context"
	"time"
)

const createOrganisationUser = `-- name: CreateOrganisationUser :exec
INSERT INTO user_organisations (user_id, organisation_id, created_on_utc, modified_on_utc)
VALUES (?1, ?2, ?3, ?4)
`

type CreateOrganisationUserParams struct {
	Userid         string
	Organisationid string
	Createdonutc   time.Time
	Modifiedonutc  time.Time
}

func (q *Queries) CreateOrganisationUser(ctx context.Context, arg CreateOrganisationUserParams) error {
	_, err := q.db.ExecContext(ctx, createOrganisationUser,
		arg.Userid,
		arg.Organisationid,
		arg.Createdonutc,
		arg.Modifiedonutc,
	)
	return err
}
