// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"
)

type Querier interface {
	CreateOrganisation(ctx context.Context, arg CreateOrganisationParams) (string, error)
	CreateOrganisationToken(ctx context.Context, arg CreateOrganisationTokenParams) (string, error)
	CreateOrganisationUser(ctx context.Context, arg CreateOrganisationUserParams) error
	CreateScimGroup(ctx context.Context, arg CreateScimGroupParams) (string, error)
	CreateScimUser(ctx context.Context, arg CreateScimUserParams) (CreateScimUserRow, error)
	GetAllScimGroups(ctx context.Context, organisationid string) ([]ScimGroup, error)
	GetAllScimUsers(ctx context.Context, organisationid string) ([]ScimUser, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetOrganisationTokenByToken(ctx context.Context, token string) (OrganisationToken, error)
	GetOrganisationTokens(ctx context.Context, organisationid string) ([]OrganisationToken, error)
	RegisterUser(ctx context.Context, arg RegisterUserParams) (string, error)
}

var _ Querier = (*Queries)(nil)
