// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"
)

type Querier interface {
	CreateOrganisation(ctx context.Context, arg CreateOrganisationParams) (string, error)
	CreateOrganisationUser(ctx context.Context, arg CreateOrganisationUserParams) error
	GetAllUsers(ctx context.Context) ([]User, error)
	RegisterUser(ctx context.Context, arg RegisterUserParams) (string, error)
}

var _ Querier = (*Queries)(nil)
